### ISSUE TITLE
bin/yolo.weights not found

### ISSUE THREAD

**Issue by maliifat** [deep-diver/YOLOv2-Train#1]
I use own dataset, and I procedure follow your GitHub but it's show bin/yolo.weights not found 
I try to fix it, but it can't fix. Before follow your blog, I used yolo-tiny, yolo-tiny-voc.cfg(pretrained model) and weight that I think they are matching. I can't fix again. 

I can't speak English well, I'm Asia 
please help me.

**Comment by maliifat** [comment]
![image](https://user-images.githubusercontent.com/43317905/45597776-3a3ff500-b9fb-11e8-8feb-13e972f2b290.png)

**Comment by maliifat** [comment]
when I run in cmd it's show Over-read bin/yolo.weights

**Comment by maliifat** [comment]
![image](https://user-images.githubusercontent.com/43317905/45597797-5e9bd180-b9fb-11e8-9443-4d7b2ff23e6d.png)

In Pycharm it's show above

**Comment by deep-diver** [comment]
Sorry for the late response. 

I think you don't have `yolo.weights` file in the `bin` directory. Follow the instruction to download the file, and you need to save it into the `bin` directory.
