### ISSUE TITLE
How to change the epoch value

### ISSUE THREAD

**Issue by suravijayjilla** [deep-diver/YOLOv2-Train#13]
Hi, 

I want to change my epoch value. But I didn't find any parameter related to this.
Please help me on this.

**Comment by deep-diver** [comment]
check this out

options = {"model": "cfg/yolo_custom.cfg", 
           "load": "bin/yolo.weights",
           "batch": 8,
           "epoch": 100,
           "gpu": 1.0,
           "train": True,
           "annotation": "./annotations/",
           "dataset": "./images/"}

**Comment by suravijayjilla** [comment]
hi,

Thanks for your valuable reply..
